### ISSUE TITLE
submission

### ISSUE THREAD

**Issue by JiaweiZhao-git** [OpenDriveLab/OpenLane-V2#26]
Great work! I encountered some errors when submitting the pkl file, I am not sure if it is a script error or a parameter error.

My test script:

`bash ./tools/dist_test.sh projects/openlanev2/configs/baseline_large.py work_dirs/baseline_large/epoch_24.pth 8  --eval bbox --eval-options dump=True dump_dir=work_dirs/baseline_large`

My test data config:
```
    test=dict(
        type=dataset_type,
        data_root=data_root,
        meta_root=meta_root,
        collection='data_dict_subset_A_val',
        pipeline=test_pipeline,
        test_mode=True),
```

After submitting the result.pkl:
```
Traceback (most recent call last):
  File "/code/scripts/workers/submission_worker.py", line 500, in run_submission
    submission_metadata=submission_serializer.data,
  File "/tmp/tmpigcmv59_/compute/challenge_data/challenge_1925/main.py", line 58, in evaluate
    raise Exception(f'The submission file size is limited to 500 MB.')
Exception: The submission file size is limited to 500 MB.
```
Thanks for your help!

**Comment by faikit** [comment]
Hi, the error message indicates that your submitted file is too large. Maybe consider some measures like reducing the number of points which describe a centerline or reducing the number of prediction for a single frame.

**Comment by JiaweiZhao-git** [comment]
Thanks for your suggestion! 
To submit on evalai, I should upload the result of the test set?  I encountered some errors on test set, I am not sure whether I use the right script args?
 My test script:
`bash ./tools/dist_test.sh projects/openlanev2/configs/baseline_large.py work_dirs/baseline_large/epoch_24.pth 8 --format-only --eval-options dump=True dump_dir=work_dirs/baseline_large/`

My test data config: change 'val' to 'test'
```
    test=dict(
        type=dataset_type,
        data_root=data_root,
        meta_root=meta_root,
        collection='data_dict_subset_A_test',
        pipeline=test_pipeline,
        test_mode=True),
```
Part of error logs:
```
  File "./tools/test.py", line 260, in <module>
    main()
  File "./tools/test.py", line 236, in main
    outputs = multi_gpu_test(model, data_loader, args.tmpdir,
  File "anaconda/envs/openlanev2/lib/python3.8/site-packages/mmdet/apis/test.py", line 107, in multi_gpu_test
    for i, data in enumerate(data_loader):
  File "anaconda/envs/openlanev2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "anaconda/envs/openlanev2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
```
```
  File "anaconda/envs/openlanev2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "mmdetection3d/mmdet3d/datasets/custom_3d.py", line 433, in __getitem__
    return self.prepare_test_data(idx)
  File "mmdetection3d/mmdet3d/datasets/custom_3d.py", line 245, in prepare_test_data
    input_dict = self.get_data_info(index)
  File "mmdetection3d/projects/openlanev2/baseline/datasets/openlane_v2_dataset.py", line 292, in get_data_info
    input_dict.update(self.get_ann_info(index))
  File "mmdetection3d/projects/openlanev2/baseline/datasets/openlane_v2_dataset.py", line 301, in get_ann_info
    gt_lc = np.array([lc['points'] for lc in frame.get_annotations_lane_centerlines()], dtype=np.float32)
TypeError: 'NoneType' object is not iterable
```
Thanks for your help!

**Comment by faikit** [comment]
I think that is cause by empty prediction, maybe you can filter them out.

**Comment by JiaweiZhao-git** [comment]
Is my test script right? the error logs seem happened in the loading annotation step, got None without annotation in the test set. Could you provide a sample script for evalai submission?
Thanks for your help!

**Comment by faikit** [comment]
Hi, I just notice that you use `--format-only`, please use `--eval *` instead.

**Comment by JiaweiZhao-git** [comment]
use` --eval * ` requires annotations when loading the test set in [get_ann_info](https://github.com/OpenDriveLab/OpenLane-V2/blob/a25dae82ac5f830196f7d63b65578b4051eeba46/plugin/mmdet3d/baseline/datasets/openlane_v2_dataset.py#L296).
 However, the test set does not have annotations.

data loader error logs:
```
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File " anaconda/envs/openlanev2/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File " anaconda/envs/openlanev2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File " anaconda/envs/openlanev2/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File " BEV/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 433, in __getitem__
    return self.prepare_test_data(idx)
  File " BEV/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 245, in prepare_test_data
    input_dict = self.get_data_info(index)
  File "BEV/mmdetection3d/projects/openlanev2/baseline/datasets/openlane_v2_dataset.py", line 292, in get_data_info
    input_dict.update(self.get_ann_info(index))
  File "BEV/mmdetection3d/projects/openlanev2/baseline/datasets/openlane_v2_dataset.py", line 301, in get_ann_info
    gt_lc = np.array([lc['points'] for lc in frame.get_annotations_lane_centerlines()], dtype=np.float32)
TypeError: 'NoneType' object is not iterable
```

**Comment by faikit** [comment]
Do you also include `--eval-options dump=True dump_dir=/PATH/TO/DUMP` to save the result?

**Comment by JiaweiZhao-git** [comment]
Yes, my test script is as follows:
`bash ./tools/dist_test.sh projects/openlanev2/configs/baseline_large.py work_dirs/baseline_large/epoch_24.pth 8 --eval * --eval-options dump=True dump_dir=work_dirs/baseline_large/`

The error seems to happened before evaluate:
```
[                                                  ] 0/4816, elapsed: 0s, ETA:Traceback (most recent call last):
  File "./tools/test.py", line 260, in <module>
    main()
  File "./tools/test.py", line 236, in main
    outputs = multi_gpu_test(model, data_loader, args.tmpdir,
  File "anaconda/envs/openlanev2/lib/python3.8/site-packages/mmdet/apis/test.py", line 107, in multi_gpu_test
    for i, data in enumerate(data_loader):
  File "anaconda/envs/openlanev2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "anaconda/envs/openlanev2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "anaconda/envs/openlanev2/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "anaconda/envs/openlanev2/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
```

**Comment by faikit** [comment]
Hi, I think just comment this [line](https://github.com/OpenDriveLab/OpenLane-V2/blob/master/plugin/mmdet3d/baseline/datasets/openlane_v2_dataset.py#L292) would help.

**Comment by faikit** [comment]
Hi, the results are stored at this [line](https://github.com/OpenDriveLab/OpenLane-V2/blob/master/plugin/mmdet3d/baseline/datasets/openlane_v2_dataset.py#L347), which is before the line 360. You can just ignore the error.

**Comment by faikit** [comment]
Hi, for evaluation, we use 11 points for each certerline. As for the performance, you can try that out on the val set.
