### ISSUE TITLE
mmdetection3d cannot start training ？

### ISSUE THREAD

**Issue by MenSanYan** [OpenDriveLab/OpenLane-V2#61]
I use "python tools/train.py projects/openlanev2/configs/baseline.py" to start training, while an error is raised.
Traceback (most recent call last):
  File "/home/ooxx/miniconda3/envs/openlanev2/lib/python3.8/site-packages/mmcv/utils/misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/home/ooxx/miniconda3/envs/openlanev2/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/mmdetection3d/projects/openlanev2/baseline/__init__.py", line 2, in <module>
    from .datasets import *
  File "/data/mmdetection3d/projects/openlanev2/baseline/datasets/__init__.py", line 2, in <module>
    from .openlane_v2_dataset import *
  File "/data/mmdetection3d/projects/openlanev2/baseline/datasets/openlane_v2_dataset.py", line 34, in <module>
    from openlanev2.dataset import Collection
ModuleNotFoundError: No module named 'openlanev2.dataset'

What should I do to fix this ?

**Comment by faikit** [comment]
Hi, currently the plug-in model requires the v1.0.0 version of the code base.
________________________________
寄件者: HelloGit ***@***.***>
寄件日期: Tuesday, August 1, 2023 9:47:51 AM
收件者: OpenDriveLab/OpenLane-V2 ***@***.***>
副本: Subscribed ***@***.***>
主旨: [OpenDriveLab/OpenLane-V2] mmdetection3d cannot start training ？ (Issue #61)


I use "python tools/train.py projects/openlanev2/configs/baseline.py" to start training, while an error is raised.
Traceback (most recent call last):
File "/home/ooxx/miniconda3/envs/openlanev2/lib/python3.8/site-packages/mmcv/utils/misc.py", line 73, in import_modules_from_strings
imported_tmp = import_module(imp)
File "/home/ooxx/miniconda3/envs/openlanev2/lib/python3.8/importlib/init.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1014, in _gcd_import
File "", line 991, in _find_and_load
File "", line 975, in _find_and_load_unlocked
File "", line 671, in _load_unlocked
File "", line 843, in exec_module
File "", line 219, in _call_with_frames_removed
File "/data/mmdetection3d/projects/openlanev2/baseline/init.py", line 2, in
from .datasets import *
File "/data/mmdetection3d/projects/openlanev2/baseline/datasets/init.py", line 2, in
from .openlane_v2_dataset import *
File "/data/mmdetection3d/projects/openlanev2/baseline/datasets/openlane_v2_dataset.py", line 34, in
from openlanev2.dataset import Collection
ModuleNotFoundError: No module named 'openlanev2.dataset'

What should I do to fix this ?

―

**Comment by MenSanYan** [comment]
@faikit I use the v1.0.0 version of the code base, while another error is raised.
Traceback (most recent call last):
  File "tools/train.py", line 263, in <module>
    main()
  File "tools/train.py", line 119, in main
    cfg = Config.fromfile(args.config)
  File "/home/ooxx/miniconda3/envs/openlanev2/lib/python3.8/site-packages/mmcv/utils/config.py", line 340, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename,
  File "/home/ooxx/miniconda3/envs/openlanev2/lib/python3.8/site-packages/mmcv/utils/config.py", line 183, in _file2dict
    check_file_exist(filename)
  File "/home/mi/miniconda3/envs/openlanev2/lib/python3.8/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/data/mmdetection3d/projects/openlanev2/configs/baseline.py" does not exist

What should I do to fix this ?

**Comment by faikit** [comment]
Please check the file structure, it is a little bit strange that the mmdetection3d folder is under the data folder.
________________________________
寄件者: HelloGit ***@***.***>
寄件日期: Tuesday, August 1, 2023 10:15:10 AM
收件者: OpenDriveLab/OpenLane-V2 ***@***.***>
副本: faikit ***@***.***>; Mention ***@***.***>
主旨: Re: [OpenDriveLab/OpenLane-V2] mmdetection3d cannot start training ？ (Issue #61)


@faikit<https://github.com/faikit> I use the v1.0.0 version of the code base, while another error is raised.
Traceback (most recent call last):
File "tools/train.py", line 263, in
main()
File "tools/train.py", line 119, in main
cfg = Config.fromfile(args.config)
File "/home/ooxx/miniconda3/envs/openlanev2/lib/python3.8/site-packages/mmcv/utils/config.py", line 340, in fromfile
cfg_dict, cfg_text = Config._file2dict(filename,
File "/home/ooxx/miniconda3/envs/openlanev2/lib/python3.8/site-packages/mmcv/utils/config.py", line 183, in _file2dict
check_file_exist(filename)
File "/home/mi/miniconda3/envs/openlanev2/lib/python3.8/site-packages/mmcv/utils/path.py", line 23, in check_file_exist
raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/data/mmdetection3d/projects/openlanev2/configs/baseline.py" does not exist

What should I do to fix this ?

―

**Comment by MenSanYan** [comment]
@faikit Thank you very much! Folder OpenLane-V2 should be inside folder mmdetection3d, and training is ok now.
