### ISSUE TITLE
ModuleNotFoundError: No module named 'openlanev2.evaluation'

### ISSUE THREAD

**Issue by Benson722** [OpenDriveLab/OpenLane-V2#90]
Thank you for your great job! 

When I try to run the **dist_train.py** , some errors occurred:

**dash:**

```
`(openlanev2) zhangyiqing@inin:~/mmdetection3d$ ./tools/dist_train.sh projects/configs/topomlp_setA_r50_wo_yolov8.py 8 --work-dir=./work_dirs/topomlp_setA_r50_wo_yolov8
WARNING:__main__:*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "./tools/train.py", line 10, in <module>
    from openlanev2.evaluation import evaluate as openlanev2_evaluate
ModuleNotFoundError: No module named 'openlanev2.evaluation'
Traceback (most recent call last):
  File "./tools/train.py", line 10, in <module>
    from openlanev2.evaluation import evaluate as openlanev2_evaluate
ModuleNotFoundError: No module named 'openlanev2.evaluation'
Traceback (most recent call last):
  File "./tools/train.py", line 10, in <module>
    from openlanev2.evaluation import evaluate as openlanev2_evaluate
ModuleNotFoundError: No module named 'openlanev2.evaluation'
Traceback (most recent call last):
  File "./tools/train.py", line 10, in <module>
    from openlanev2.evaluation import evaluate as openlanev2_evaluate
ModuleNotFoundError: No module named 'openlanev2.evaluation'
Traceback (most recent call last):
  File "./tools/train.py", line 10, in <module>
    from openlanev2.evaluation import evaluate as openlanev2_evaluate
ModuleNotFoundError: No module named 'openlanev2.evaluation'
Traceback (most recent call last):
  File "./tools/train.py", line 10, in <module>
    from openlanev2.evaluation import evaluate as openlanev2_evaluate
ModuleNotFoundError: No module named 'openlanev2.evaluation'
Traceback (most recent call last):
  File "./tools/train.py", line 10, in <module>
    from openlanev2.evaluation import evaluate as openlanev2_evaluate
ModuleNotFoundError: No module named 'openlanev2.evaluation'
Traceback (most recent call last):
  File "./tools/train.py", line 10, in <module>
    from openlanev2.evaluation import evaluate as openlanev2_evaluate
ModuleNotFoundError: No module named 'openlanev2.evaluation'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1295863) of binary: /home/zhangyiqing/miniconda3/envs/openlanev2/bin/python
/home/zhangyiqing/miniconda3/envs/openlanev2/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py:367: UserWarning:

**********************************************************************
               CHILD PROCESS FAILED WITH NO ERROR_FILE
**********************************************************************
CHILD PROCESS FAILED WITH NO ERROR_FILE
Child process 1295863 (local_rank 0) FAILED (exitcode 1)
Error msg: Process failed with exitcode 1
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
**********************************************************************
  warnings.warn(_no_error_file_warning_msg(rank, failure))
Traceback (most recent call last):
  File "/home/zhangyiqing/miniconda3/envs/openlanev2/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zhangyiqing/miniconda3/envs/openlanev2/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zhangyiqing/miniconda3/envs/openlanev2/lib/python3.8/site-packages/torch/distributed/run.py", line 702, in <module>
    main()
  File "/home/zhangyiqing/miniconda3/envs/openlanev2/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 361, in wrapper
    return f(*args, **kwargs)
  File "/home/zhangyiqing/miniconda3/envs/openlanev2/lib/python3.8/site-packages/torch/distributed/run.py", line 698, in main
    run(args)
  File "/home/zhangyiqing/miniconda3/envs/openlanev2/lib/python3.8/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/home/zhangyiqing/miniconda3/envs/openlanev2/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zhangyiqing/miniconda3/envs/openlanev2/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
***************************************
        ./tools/train.py FAILED
=======================================
Root Cause:
[0]:
  time: 2024-01-15_10:47:21
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 1295863)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
[1]:
  time: 2024-01-15_10:47:21
  rank: 1 (local_rank: 1)
  exitcode: 1 (pid: 1295864)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[2]:
  time: 2024-01-15_10:47:21
  rank: 2 (local_rank: 2)
  exitcode: 1 (pid: 1295865)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[3]:
  time: 2024-01-15_10:47:21
  rank: 3 (local_rank: 3)
  exitcode: 1 (pid: 1295866)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[4]:
  time: 2024-01-15_10:47:21
  rank: 4 (local_rank: 4)
  exitcode: 1 (pid: 1295867)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[5]:
  time: 2024-01-15_10:47:21
  rank: 5 (local_rank: 5)
  exitcode: 1 (pid: 1295868)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[6]:
  time: 2024-01-15_10:47:21
  rank: 6 (local_rank: 6)
  exitcode: 1 (pid: 1295869)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[7]:
  time: 2024-01-15_10:47:21
  rank: 7 (local_rank: 7)
  exitcode: 1 (pid: 1295870)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
***************************************
`
```

My environment is :

```
mmcv-full                 1.5.2
mmdet                     2.26.0
mmdet3d                   1.0.0rc6             /home/zhangyiqing/mmdetection3d
mmsegmentation            0.29.1
```

Looking forward to your help! Thank you.

Best regards

**Comment by sephyli** [comment]
The plugin model currently does not support the v2.x version of OpenLane-V2.

You can checkout to v1.1.0 of OpenLane-V2 repo, or install v1.1.0 from pip to fix this.

**Comment by Benson722** [comment]
Thank you for your answer! It works for me. :)
